export const keyWords = [
  "Contour Cosmetic Clinic Bangalore",
  "best hair clinic Bangalore",
  "hair transplant Bangalore",
  "hair restoration Bangalore",
  "skin clinic Bangalore",
  "PRP treatment Bangalore",
  "GFC therapy Bangalore",
  "laser skin treatment Bangalore",
  "derma fillers Bangalore",
  "BTM Layout cosmetic clinic",
  "cosmetic dermatologist Bangalore",
  "hair loss treatment Bangalore",
  "aesthetic clinic Bangalore",
  "hair regrowth Bangalore",
  "best hair clinic BTM Layout",
  "hair transplant BTM Layout",
  "derma fillers BTM Layout",
  "PRP treatment BTM Layout",
  "hair regrowth BTM Layout",
];

export const seoKeywords = [
  "Contour Cosmetic Clinic",
  "Contour Clinic BTM Layout",
  "Cosmetic clinic Bengaluru",
  "Cosmetic surgery Bengaluru",
  "Aesthetic clinic Bengaluru",
  "Best cosmetic clinic BTM Layout",
  "Top cosmetic clinic Bengaluru",
  "Cosmetic doctor BTM Layout",
  "Contour Clinic Karnataka",
  "Cosmetic specialist Bengaluru",
  "Hair transplant BTM Layout",
  "Hair transplant Bengaluru",
  "FUE hair transplant Bengaluru",
  "FUT hair transplant Bengaluru",
  "Best hair transplant BTM Layout",
  "Affordable hair transplant Bengaluru",
  "Hair restoration Bengaluru",
  "Hair growth treatment BTM Layout",
  "Hair loss treatment Bengaluru",
  "Scalp treatment BTM Layout",
  "Hair transplant cost Bengaluru",
  "Hair transplant surgeon BTM Layout",
  "Advanced hair treatments Bengaluru",
  "Natural hair transplant BTM Layout",
  "Hair clinic near me Bengaluru",
  "Skin clinic BTM Layout",
  "Dermatology clinic Bengaluru",
  "Skin rejuvenation BTM Layout",
  "Anti-aging skin treatment Bengaluru",
  "Acne treatment BTM Layout",
  "Scar removal clinic Bengaluru",
  "Skin whitening treatment BTM Layout",
  "Pigmentation treatment Bengaluru",
  "Laser skin treatment BTM Layout",
  "Skin tightening treatment Bengaluru",
  "Facial skin care clinic BTM Layout",
  "Best dermatologist Bengaluru",
  "Cosmetic dermatology BTM Layout",
  "Skin therapy Bengaluru",
  "Advanced skin care clinic BTM Layout",
  "Facial enhancement BTM Layout",
  "Botox treatment Bengaluru",
  "Dermal fillers BTM Layout",
  "Wrinkle removal Bengaluru",
  "Facial contouring BTM Layout",
  "Non-surgical facelift Bengaluru",
  "Lip enhancement BTM Layout",
  "Cheek enhancement Bengaluru",
  "Nose reshaping BTM Layout",
  "Jawline enhancement Bengaluru",
  "Facial aesthetics clinic BTM Layout",
  "Anti-wrinkle treatment Bengaluru",
  "Skin resurfacing BTM Layout",
  "Chemical peel treatment Bengaluru",
  "Facial rejuvenation BTM Layout",
  "Best cosmetic clinic in BTM Layout Bengaluru",
  "Affordable cosmetic treatments BTM Layout",
  "Experienced cosmetic doctors Bengaluru",
  "Safe hair transplant procedure BTM Layout",
  "Advanced skin rejuvenation treatment Bengaluru",
  "Non-surgical facial enhancement clinic BTM Layout",
  "Professional dermatology services Bengaluru",
  "Top-rated cosmetic clinic BTM Layout",
  "Hair and skin treatment clinic Bengaluru",
  "Personalized cosmetic treatments BTM Layout",
  "Cosmetic surgery consultation Bengaluru",
  "Natural-looking hair transplant BTM Layout",
  "Laser skin resurfacing clinic Bengaluru",
  "Anti-aging clinic BTM Layout",
  "Best acne treatment clinic Bengaluru",
  "Contour Clinic 80 Ft Road BTM Layout",
  "Cosmetic clinic Vishweshwaraiah Road Bengaluru",
  "Hair transplant 6th Stage BTM Layout",
  "Skin treatment Phase 2 BTM Layout",
  "Botox clinic BTM Layout Bengaluru",
  "FUE hair transplant Phase 2 BTM Layout",
  "Acne treatment near me BTM Layout",
  "Facial aesthetics clinic 2nd Floor Lakshmidevi Complex",
  "Non-surgical facelift BTM Layout Bengaluru",
  "Dermatology clinic 6th Stage BTM Layout",
  "Cosmetic clinic contact +91 98765 43210",
  "Book appointment Contour Clinic BTM Layout",
  "Cosmetic consultation Bengaluru phone",
  "Hair transplant booking BTM Layout",
  "Skin treatment appointment Bengaluru",
  "Email info@contourclinic.com",
  "Cosmetic surgery consultation BTM Layout",
  "Schedule cosmetic treatment Bengaluru",
  "Contact Contour Clinic BTM Layout",
  "Cosmetic doctor consultation BTM Layout",
  "Cosmetic surgery BTM Layout",
  "Cosmetic procedures Bengaluru",
  "Skin care solutions BTM Layout",
  "Hair care solutions Bengaluru",
  "Facial care services BTM Layout",
  "Aesthetic procedures Bengaluru",
  "Medical aesthetics BTM Layout",
  "Laser treatments Bengaluru",
  "Anti-aging solutions BTM Layout",
  "Scar removal clinic Bengaluru",
  "Wrinkle removal BTM Layout",
  "Pigmentation removal Bengaluru",
  "Skin health clinic BTM Layout",
  "Hair specialist clinic Bengaluru",
  "Hair doctor near me BTM Layout",
];
